version: '3.8'

services:
  forum_postgres:
    container_name: forum_app_postgres
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - ${ADDR}:${ADDR}
    environment:
      IN_MEMORY: "false"
      POSTGRES_URL: ${POSTGRES_URL}

  postgres:
    container_name: forum_db_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}